---
# Ubuntu/Debian specific variables
webserver_packages:
  nginx:
    - nginx
    - nginx-common
    - nginx-core
  apache:
    - apache2
    - apache2-utils

webserver_service:
  nginx: nginx
  apache: apache2

webserver_config_dir:
  nginx: /etc/nginx
  apache: /etc/apache2

webserver_log_dir:
  nginx: /var/log/nginx
  apache: /var/log/apache2

firewall_service: ufw
